networks:
  medical-app-dev:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}-network"

services:

  webserver:
    build:
      context: "docker/webserver"
    container_name: "${COMPOSE_PROJECT_NAME}-web"
    restart: "no"
    ports:
      - "${HOST_MACHINE_WEB_PORT}:80"
    links:
      - database
    volumes:
      - .:/var/www/html
      - ./docker/webserver/conf.d/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/webserver/xdebug.sh:/usr/local/bin/xdebug.sh
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: ${PHP_OPCACHE_MAX_WASTED_PERCENTAGE}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
      PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES}
      PHP_IDE_CONFIG: "serverName=localhost"
      COMPOSER_AUTH: ${COMPOSER_AUTH}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    build:
      context: "docker/database"
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    restart: "no"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - persistent-database:/var/lib/mysql

# ensemble des volumes persistants
volumes:
  persistent-database:
